import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import os
from fpdf import FPDF

# ---------------------- PDF Generation ----------------------

def generate_cover_letter_pdf(cover_text, filename="Cover_Letter.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)
    for line in cover_text.split('\n'):
        pdf.multi_cell(0, 10, line)
    pdf.output(filename)
    print(f"✅ Cover letter PDF saved as: {filename}")

def generate_qa_pdf(qa_dict, filename="QA_Match.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)
    for q, a in qa_dict.items():
        pdf.multi_cell(0, 10, f"Q: {q}")
        pdf.multi_cell(0, 10, f"A: {a}\n")
    pdf.output(filename)
    print(f"✅ Q&A PDF saved as: {filename}")

# ---------------------- Email Sending ----------------------

def send_email_with_attachments(sender_email, sender_password, receiver_email, subject, body, attachment_paths):
    msg = MIMEMultipart()
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    for path in attachment_paths:
        try:
            with open(path, "rb") as f:
                part = MIMEApplication(f.read(), Name=os.path.basename(path))
                part['Content-Disposition'] = f'attachment; filename="{os.path.basename(path)}"'
                msg.attach(part)
        except Exception as e:
            print(f"❌ Error attaching file {path}: {e}")
            return

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender_email, sender_password)
            server.send_message(msg)
        print("✅ Email sent successfully.")
    except Exception as e:
        print(f"❌ Error sending email: {e}")

# ---------------------- Run Everything ----------------------

cover_letter = """
Dear Hiring Manager,

I am writing to express my interest in the AI Developer position at your esteemed organization.
With my experience in deep learning, NLP, and Python, I am confident I can contribute effectively...

Sincerely,
Chanti Babu Sambangi
"""

qa_pairs = {
    "What makes you a good fit for this role?": "I have built multiple AI projects...",
    "How do your skills match the JD?": "I am proficient in Python, PyTorch, and have done image classification...",
}

# Generate PDFs
generate_cover_letter_pdf(cover_letter, "Cover_Letter.pdf")
generate_qa_pdf(qa_pairs, "QA_Match.pdf")

# Email Setup
sender_email = "agenticai.cbs@gmail.com"
# Gmail app password
import os
sender_password = os.getenv("EMAIL_APP_PASSWORD")  
receiver_email = "chantibabusambangi@gmail.com"
subject = "Agentic AI Report"
body = "Please find the attached PDF report generated by the AI agent."

# Attachments: cover letter, Q&A, and resume
attachments = [
    "Cover_Letter.pdf",
    "QA_Match.pdf"
]

# Send the email
send_email_with_attachments(sender_email, sender_password, receiver_email, subject, body, attachments)
